#!/usr/bin/env bash
set -euo pipefail

# Regenerated by `inv configure` — do not hand-edit. Installs the repo-tasks version this repo
# was last configured against. For CI and reproducibility archaeology only: a human working
# locally runs `inv repo-tasks.update` instead, which moves the shared *global* install forward.
# Re-running this script by habit would silently reinstall the global tool to whatever version
# *this* repo last pinned, yanking it out from under any other repo just being worked on.

command -v uv > /dev/null 2>&1 || {
  echo "uv not found on PATH — install uv first" >&2
  exit 1
}
uv tool install --force --with-executables-from invoke 'repo-tasks @ git+https://github.com/TheodoreAD/repo-tasks'
